[target.aarch64-unknown-linux-musl]
image = "local/cross:aarch64-unknown-linux-musl"

[target.armv7-unknown-linux-musleabihf]
image = "local/cross:armv7-unknown-linux-musleabihf"

[target.x86_64-unknown-linux-musl]
image = "local/cross:x86_64-unknown-linux-musl"

[target.x86_64-unknown-freebsd]
image = "local/cross:x86_64-unknown-freebsd"
